project_id = "ntvgthwqxixkoemyxhqo"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://id-preview--92a66252-fc6d-4ee5-a1ec-64acd67ce189.lovable.app"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[functions.process-ocr]
verify_jwt = false

[functions.pix-auth]
verify_jwt = false

[functions.pix-pay-dict]
verify_jwt = false

[functions.pix-pay-qrc]
verify_jwt = false

[functions.pix-qrc-info]
verify_jwt = false

[functions.pix-check-status]
verify_jwt = false

[functions.pix-webhook]
verify_jwt = false

[functions.pix-receipt]
verify_jwt = false

[functions.pix-refund]
verify_jwt = false

[functions.billet-pay]
verify_jwt = false

[functions.billet-check-status]
verify_jwt = false

[functions.billet-receipt]
verify_jwt = false

[functions.pix-balance]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.generate-pix-receipt]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.billet-consult]
verify_jwt = false

[functions.pix-dict-lookup]
verify_jwt = false

[functions.register-transfeera-webhook]
verify_jwt = false

[functions.batch-pay]
verify_jwt = false

[functions.pix-webhook-gateway]
verify_jwt = false

[functions.internal-payment-webhook]
verify_jwt = false
